[project]
name = "beatport-mcp"
version = "0.1.0"
description = "MCP for Beatport developer API."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.5.0",
    "requests>=2.32.3",
]
